apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-ha.fullname" . }}-init-s3-env-secret
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "redis-ha.fullname" . }}
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: "{{ .Values.restore.s3.secret_key | b64enc }}"
