apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-ha.fullname" . }}-init-s3-env-cm
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "redis-ha.fullname" . }}
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.restore.s3.access_key }}"
