{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "redis-ha.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "labels.standard" . | indent 4 }}
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:
    - 'policy'
  resources:
    - 'podsecuritypolicies'
  verbs:
    - 'use'
  resourceNames:
    - {{ template "redis-ha.fullname" . }}
{{- end }}
{{- end }}
