apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex-tenant.fullname" . }}-cm
data:
  cortex-tenant.yml: |
    # Where to listen for incoming write requests from Prometheus
    listen: 0.0.0.0:8080
    # Profiling API, remove to disable
    listen_pprof: 0.0.0.0:7008
    # Where to send the modified requests (Cortex)
    target: {{ .Values.cortex.pushUrl }}
    # Log level
    log_level: {{ default "warn" .Values.logLevel }}
    # HTTP request timeout
    timeout: 10s
    # Timeout to wait on shutdown to allow load balancers detect that we're going away.
    # During this period after the shutdown command the /alive endpoint will reply with HTTP 503.
    # Set to 0s to disable.
    timeout_shutdown: 10s

    tenant:
      # Which label to look for the tenant information
      label: {{ default "tenant" .Values.cortex.tenant.label }}
      # Whether to remove the tenant label from the request
      label_remove: {{ default false .Values.cortex.tenant.removeLabel }}
      # To which header to add the tenant ID
      header: {{ default "X-Scope-OrgID" .Values.cortex.tenant.header }}
      # Which tenant ID to use if the label is missing in any of the timeseries
      # If this is not set or empty then the write request with missing tenant label
      # will be rejected with HTTP code 400
      default: {{ default "no_tenant" .Values.cortex.tenant.defaultTenant }}
      accept_all: {{ default false .Values.cortex.tenant.acceptAll }}